ARG BASE_TAG="20.04-desktop"
ARG BASE_IMAGE="fakebilly/ubuntu"
FROM $BASE_IMAGE:$BASE_TAG

LABEL maintainer="fakebilly.work@outlook.com"
LABEL org.opencontainers.image.authors="FakeBilly"

WORKDIR /root
USER root

ENV KASM_USER=monet \
    DEBIAN_FRONTEND=noninteractive \
    STARTUPDIR=/dockerstartup \
    NODE_VERSION=v16.20.2 \
    NVM_BIN=/usr/local/nvm/versions/node/$NODE_VERSION/bin \
    NVM_DIR=/usr/local/nvm \
    DEFAULT_PROFILE_HOME=/home/kasm-default-profile \
    STARTUPDIR=/dockerstartup \
    INST_DIR=$STARTUPDIR/install

ARG CUSTOME_INST_SCRIPTS="/ubuntu/install/jdk/install_jdk.sh \
                  /ubuntu/install/maven/install_maven.sh \
                  /ubuntu/install/nvm/install_nvm_0_39_5.sh \
                  /ubuntu/install/pyenv/install_pyenv_2_3_28.sh \
                  /ubuntu/install/git/install_git_2_36.sh \
                  /ubuntu/install/jetbrains/idea/install_idea_2021_3.sh \
                  /ubuntu/install/jetbrains/datagrip/install_datagrop_2019_3.sh \
                  /ubuntu/install/jetbrains/pycharm/install_pycharm_2019_3.sh \
                  /ubuntu/install/jetbrains/webstorm/install_webstorm_2019_3.sh"


COPY ./src/ $INST_DIR

RUN  \
    for SCRIPT in $CUSTOME_INST_SCRIPTS; do \
        bash ${INST_DIR}${SCRIPT}; \
    done  \
    && bash /usr/local/nvm/install_nvm_0.39.5.sh \
    && . $NVM_DIR/nvm.sh \
    && nvm install v12.22.12 \
    && nvm install v14.21.3 \
    && nvm install $NODE_VERSION \
    && nvm install v18.18.0 \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ARG ROOT_USER=root
ARG ROOT_USER_PWD=dev1024

ENV HOME=/home/$KASM_USER \
    TZ=Asia/Hong_Kong

RUN echo "${ROOT_USER}:${ROOT_USER_PWD}" | sudo chpasswd \
    && chown -R $KASM_USER:$KASM_USER $HOME/ \
    && echo '\n\
LANG=en_US.UTF-8\n\
LANGUAGE=en_US.UTF-8\n\
LC_CTYPE=en_US.UTF-8\n\
LC_NUMERIC=en_US.UTF-8\n\
LC_TIME=en_US.UTF-8\n\
LC_COLLATE=en_US.UTF-8\n\
LC_MONETARY=en_US.UTF-8\n\
LC_MESSAGES=en_US.UTF-8\n\
LC_PAPER=en_US.UTF-8\n\
LC_NAME=en_US.UTF-8\n\
LC_ADDRESS=en_US.UTF-8\n\
LC_TELEPHONE=en_US.UTF-8\n\
LC_MEASUREMENT=en_US.UTF-8\n\
LC_IDENTIFICATION=en_US.UTF-8\n\
LC_ALL=en_US.UTF-8\n\
\n\
STARTUPDIR=/dockerstartup\n\
TZ=Asia/Hong_Kong' >> /etc/environment \
    && mv $INST_DIR/ubuntu/startup_scripts/custom_startup.sh $STARTUPDIR/custom_startup.sh \
    && chmod +x $STARTUPDIR/custom_startup.sh && chown $KASM_USER:$KASM_USER $STARTUPDIR/custom_startup.sh \
    && ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime

WORKDIR $HOME

USER $KASM_USER
